<%
'==============================================================================
' Author: Ken Wallace, Principal - Ken Wallace Design
'==============================================================================
function getFileIcon(strFileName, bitIconSize, bitIsPublished)

	'strFileName	= [Any Legal String] if filename ends in an extension, this
	'									 script will find the appropriate 
	'									 extension and assigned icon.
	
	'bitIconSize	= 0 = SMALL ICON
	'bitIconSize	= 1 = LARGE ICON
	'bitIsPublished = 0 = FALSE (Not Published)
	'bitIsPublished = 1 = TRUE (Published)
	
	
	'Declare In Memory
	Dim strFileExt, strFileMIME
	Dim strIconName_Small
	Dim strIconName_Small_Published
	Dim strIconName_Large
	Dim strIconName_Large_Published
	
	'Set Defaults
	strFileExt = ""
	strFileMIME = ""

	strIconName_Small = ""
	strIconName_Small_Published = ""
	strIconName_Large = ""
	strIconName_Large_Published = ""
	
	if not IsNull(strFileName) then
		
		strFileName = Trim(LCase(strFileName))
		if Instr(strFileName, ".") > 0 then
			strFileExt = Mid(strFileName, InStrRev(strFileName, "."), Len(strFileName))
		else
			strFileExt = ""
		end if
		
		Select Case strFileExt
			Case ".3dm"
				strFileMIME = "x-world/x-3dmf"
			Case ".3dmf"
				strFileMIME = "x-world/x-3dmf"
			Case ".a"
				strFileMIME = "application/octet-stream"
			Case ".aab"
				strFileMIME = "application/x-authorware-bin"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".aam"
				strFileMIME = "application/x-authorware-map"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".aas"
				strFileMIME = "application/x-authorware-seg"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".abc"
				strFileMIME = "text/vnd.abc"
			Case ".acgi"
				strFileMIME = "text/html"
			Case ".afl"
				strFileMIME = "video/animaflex"
			Case ".ai"
				strFileMIME = "application/postscript"
				strIconName_Small			= "icon_aillustrator_small.gif"
				strIconName_Small_Published = "icon_aillustrator_small_on.gif"
				strIconName_Large			= "icon_aillustrator_small.gif"
				strIconName_Large_Published = "icon_aillustrator_small_on.gif"
			Case ".aif"
				strFileMIME = "audio/aiff"
		'	Case ".aif"
		'		strFileMIME = "audio/x-aiff"
			Case ".aifc"
				strFileMIME = "audio/aiff"
		'	Case ".aifc"
		'		strFileMIME = "audio/x-aiff"
			Case ".aiff"
				strFileMIME = "audio/aiff"
		'	Case ".aiff"
		'		strFileMIME = "audio/x-aiff"
			Case ".aim"
				strFileMIME = "application/x-aim"
			Case ".aip"
				strFileMIME = "text/x-audiosoft-intra"
			Case ".ani"
				strFileMIME = "application/x-navi-animation"
			Case ".aos"
				strFileMIME = "application/x-nokia-9000-communicator-add-on-software"
			Case ".aps"
				strFileMIME = "application/mime"
			Case ".arc"
				strFileMIME = "application/octet-stream"
			Case ".arj"
				strFileMIME = "application/arj"
		'	Case ".arj"
		'		strFileMIME = "application/octet-stream"
			Case ".art"
				strFileMIME = "image/x-jg"
			Case ".asf"
				strFileMIME = "video/x-ms-asf"
			Case ".asm"
				strFileMIME = "text/x-asm"
			Case ".asp"
				strFileMIME = "text/asp"
			Case ".asx"
				strFileMIME = "video/x-ms-asf"
		'	Case ".asx"
		'		strFileMIME = "video/x-ms-asf-plugin"
		'	Case ".au"
		'		strFileMIME = "audio/basic"
			Case ".au"
				strFileMIME = "audio/x-au"
			Case ".avi"
				strFileMIME = "video/avi"
		'	Case ".avi"
		'		strFileMIME = "video/msvideo"
		'	Case ".avi"
		'		strFileMIME = "video/x-msvideo"
			Case ".avs"
				strFileMIME = "video/avs-video"
			Case ".bcpio"
				strFileMIME = "application/x-bcpio"
			Case ".bin"
				strFileMIME = "application/mac-binary"
		'	Case ".bin"
		'		strFileMIME = "application/macbinary"
		'	Case ".bin"
		'		strFileMIME = "application/octet-stream"
		'	Case ".bin"
		'		strFileMIME = "application/x-binary"
		'	Case ".bin"
		'		strFileMIME = "application/x-macbinary"
			Case ".bm"
				strFileMIME = "image/bmp"
			Case ".bmp"
				strFileMIME = "image/bmp"
		'	Case ".bmp"
		'		strFileMIME = "image/x-windows-bmp"
			Case ".boo"
				strFileMIME = "application/book"
			Case ".book"
				strFileMIME = "application/book"
			Case ".boz"
				strFileMIME = "application/x-bzip2"
			Case ".bsh"
				strFileMIME = "application/x-bsh"
			Case ".bz"
				strFileMIME = "application/x-bzip"
			Case ".bz2"
				strFileMIME = "application/x-bzip2"
			Case ".c"
				strFileMIME = "text/plain"
		'	Case ".c"
		'		strFileMIME = "text/x-c"
			Case ".c++"
				strFileMIME = "text/plain"
			Case ".cat"
				strFileMIME = "application/vnd.ms-pki.seccat"
			Case ".cc"
				strFileMIME = "text/plain"
		'	Case ".cc"
		'		strFileMIME = "text/x-c"
			Case ".ccad"
				strFileMIME = "application/clariscad"
			Case ".cco"
				strFileMIME = "application/x-cocoa"
			Case ".cdf"
				strFileMIME = "application/cdf"
		'	Case ".cdf"
		'		strFileMIME = "application/x-cdf"
		'	Case ".cdf"
		'		strFileMIME = "application/x-netcdf"
		'	Case ".cer"
		'		strFileMIME = "application/pkix-cert"
			Case ".cer"
				strFileMIME = "application/x-x509-ca-cert"
			Case ".cha"
				strFileMIME = "application/x-chat"
			Case ".chat"
				strFileMIME = "application/x-chat"
			Case ".class"
				strFileMIME = "application/java"
		'	Case ".class"
		'		strFileMIME = "application/java-byte-code"
		'	Case ".class"
		'		strFileMIME = "application/x-java-class"
		'	Case ".com"
		'		strFileMIME = "application/octet-stream"
			Case ".com"
				strFileMIME = "text/plain"
			Case ".conf"
				strFileMIME = "text/plain"
			Case ".cpio"
				strFileMIME = "application/x-cpio"
			Case ".cpp"
				strFileMIME = "text/x-c"
			Case ".cpt"
				strFileMIME = "application/mac-compactpro"
		'	Case ".cpt"
		'		strFileMIME = "application/x-compactpro"
		'	Case ".cpt"
		'		strFileMIME = "application/x-cpt"
		'	Case ".crl"
		'		strFileMIME = "application/pkcs-crl"
			Case ".crl"
				strFileMIME = "application/pkix-crl"
			Case ".crt"
				strFileMIME = "application/pkix-cert"
		'	Case ".crt"
		'		strFileMIME = "application/x-x509-ca-cert"
		'	Case ".crt"
		'		strFileMIME = "application/x-x509-user-cert"
		'	Case ".csh"
		'		strFileMIME = "application/x-csh"
			Case ".csh"
				strFileMIME = "text/x-script.csh"
		'	Case ".css"
		'		strFileMIME = "application/x-pointplus"
			Case ".css"
				strFileMIME = "text/css"
			Case ".cxx"
				strFileMIME = "text/plain"
			Case ".dcr"
				strFileMIME = "application/x-director"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".deepv"
				strFileMIME = "application/x-deepv"
			Case ".def"
				strFileMIME = "text/plain"
			Case ".der"
				strFileMIME = "application/x-x509-ca-cert"
			Case ".dif"
				strFileMIME = "video/x-dv"
			Case ".dir"
				strFileMIME = "application/x-director"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".dl"
				strFileMIME = "video/dl"
		'	Case ".dl"
		'		strFileMIME = "video/x-dl"
			Case ".doc"
				strFileMIME = "application/msword"
				strIconName_Small			= "icon_msword_small.gif"
				strIconName_Small_Published = "icon_msword_small_on.gif"
				strIconName_Large			= "icon_msword_small.gif"
				strIconName_Large_Published = "icon_msword_small_on.gif"
			Case ".dot"
				strFileMIME = "application/msword"
				strIconName_Small			= "icon_msword_small.gif"
				strIconName_Small_Published = "icon_msword_small_on.gif"
				strIconName_Large			= "icon_msword_small.gif"
				strIconName_Large_Published = "icon_msword_small_on.gif"
			Case ".dp"
				strFileMIME = "application/commonground"
			Case ".drw"
				strFileMIME = "application/drafting"
			Case ".dump"
				strFileMIME = "application/octet-stream"
			Case ".dv"
				strFileMIME = "video/x-dv"
			Case ".dvi"
				strFileMIME = "application/x-dvi"
		'	Case ".dwf"
		'		strFileMIME = "drawing/x-dwf"
			Case ".dwf"
				strFileMIME = "model/vnd.dwf"
			Case ".dwg"
				strFileMIME = "application/acad"
		'	Case ".dwg"
		'		strFileMIME = "image/vnd.dwg"
		'	Case ".dwg"
		'		strFileMIME = "image/x-dwg"
			Case ".dxf"
				strFileMIME = "application/dxf"
		'	Case ".dxf"
		'		strFileMIME = "image/vnd.dwg"
		'	Case ".dxf"
		'		strFileMIME = "image/x-dwg"
			Case ".dxr"
				strFileMIME = "application/x-director"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".el"
				strFileMIME = "text/x-script.elisp"
			Case ".elc"
				strFileMIME = "application/x-bytecode.elisp"
		'	Case ".elc"
		'		strFileMIME = "application/x-elc"
			Case ".env"
				strFileMIME = "application/x-envoy"
			Case ".eps"
				strFileMIME = "application/postscript"
				strIconName_Small			= "icon_aacrobat_small.gif"
				strIconName_Small_Published = "icon_aacrobat_small_on.gif"
				strIconName_Large			= "icon_aacrobat_small.gif"
				strIconName_Large_Published = "icon_aacrobat_small_on.gif"
			Case ".es"
				strFileMIME = "application/x-esrehber"
			Case ".etx"
				strFileMIME = "text/x-setext"
			Case ".evy"
				strFileMIME = "application/envoy"
		'	Case ".evy"
		'		strFileMIME = "application/x-envoy"
			Case ".exe"
				strFileMIME = "application/octet-stream"
			Case ".f"
				strFileMIME = "text/plain"
		'	Case ".f"
		'		strFileMIME = "text/x-fortran"
			Case ".f77"
				strFileMIME = "text/x-fortran"
			Case ".f90"
				strFileMIME = "text/plain"
			Case ".f90"
				strFileMIME = "text/x-fortran"
			Case ".fdf"
				strFileMIME = "application/vnd.fdf"
		'	Case ".fif"
		'		strFileMIME = "application/fractals"
			Case ".fif"
				strFileMIME = "image/fif"
			Case ".fla"
				strFileMIME = "application/x-shockwave-flash"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".fli"
				strFileMIME = "video/fli"
		'	Case ".fli"
		'		strFileMIME = "video/x-fli"
			Case ".flo"
				strFileMIME = "image/florian"
			Case ".flx"
				strFileMIME = "text/vnd.fmi.flexstor"
			Case ".fmf"
				strFileMIME = "video/x-atomic3d-feature"
			Case ".for"
				strFileMIME = "text/plain"
		'	Case ".for"
		'		strFileMIME = "text/x-fortran"
			Case ".fpx"
				strFileMIME = "image/vnd.fpx"
		'	Case ".fpx"
		'		strFileMIME = "image/vnd.net-fpx"
			Case ".frl"
				strFileMIME = "application/freeloader"
			Case ".funk"
				strFileMIME = "audio/make"
			Case ".g"
				strFileMIME = "text/plain"
			Case ".g3"
				strFileMIME = "image/g3fax"
			Case ".gif"
				strFileMIME = "image/gif"
			Case ".gl"
				strFileMIME = "video/gl"
		'	Case ".gl"
		'		strFileMIME = "video/x-gl"
			Case ".gsd"
				strFileMIME = "audio/x-gsm"
			Case ".gsm"
				strFileMIME = "audio/x-gsm"
			Case ".gsp"
				strFileMIME = "application/x-gsp"
			Case ".gss"
				strFileMIME = "application/x-gss"
			Case ".gtar"
				strFileMIME = "application/x-gtar"
			Case ".gz"
				strFileMIME = "application/x-compressed"
		'	Case ".gz"
		'		strFileMIME = "application/x-gzip"
			Case ".gzip"
				strFileMIME = "application/x-gzip"
		'	Case ".gzip"
		'		strFileMIME = "multipart/x-gzip"
			Case ".h"
				strFileMIME = "text/plain"
		''	Case ".h"
		'		strFileMIME = "text/x-h"
			Case ".hdf"
				strFileMIME = "application/x-hdf"
			Case ".help"
				strFileMIME = "application/x-helpfile"
			Case ".hgl"
				strFileMIME = "application/vnd.hp-HPGL"
			Case ".hh"
				strFileMIME = "text/plain"
		'	Case ".hh"
		'		strFileMIME = "text/x-h"
			Case ".hlb"
				strFileMIME = "text/x-script"
			Case ".hlp"
				strFileMIME = "application/hlp"
		'	Case ".hlp"
		'		strFileMIME = "application/x-helpfile"
		'	Case ".hlp"
		'		strFileMIME = "application/x-winhelp"
			Case ".hpg"
				strFileMIME = "application/vnd.hp-HPGL"
			Case ".hpgl"
				strFileMIME = "application/vnd.hp-HPGL"
			Case ".hqx"
				strFileMIME = "application/binhex"
		'	Case ".hqx"
		'		strFileMIME = "application/binhex4"
		'	Case ".hqx"
		'		strFileMIME = "application/mac-binhex"
		'	Case ".hqx"
		'		strFileMIME = "application/mac-binhex40"
		'	Case ".hqx"
		'		strFileMIME = "application/x-binhex40"
		'	Case ".hqx"
		'		strFileMIME = "application/x-mac-binhex40"
			Case ".hta"
				strFileMIME = "application/hta"
			Case ".htc"
				strFileMIME = "text/x-component"
			Case ".htm"
				strFileMIME = "text/html"
			Case ".html"
				strFileMIME = "text/html"
			Case ".htmls"
				strFileMIME = "text/html"
			Case ".htt"
				strFileMIME = "text/webviewhtml"
			Case ".htx"
				strFileMIME = "text/html"
			Case ".ice"
				strFileMIME = "x-conference/x-cooltalk"
			Case ".ico"
				strFileMIME = "image/x-icon"
			Case ".idc"
				strFileMIME = "text/plain"
			Case ".ief"
				strFileMIME = "image/ief"
			Case ".iefs"
				strFileMIME = "image/ief"
			Case ".iges"
				strFileMIME = "application/iges"
		'	Case ".iges"
		'		strFileMIME = "model/iges"
			Case ".igs"
				strFileMIME = "application/iges"
		'	Case ".igs"
		'		strFileMIME = "model/iges"
			Case ".ima"
				strFileMIME = "application/x-ima"
			Case ".imap"
				strFileMIME = "application/x-httpd-imap"
			Case ".inf"
				strFileMIME = "application/inf"
			Case ".ins"
				strFileMIME = "application/x-internett-signup"
			Case ".ip"
				strFileMIME = "application/x-ip2"
			Case ".isu"
				strFileMIME = "video/x-isvideo"
			Case ".it"
				strFileMIME = "audio/it"
			Case ".iv"
				strFileMIME = "application/x-inventor"
			Case ".ivr"
				strFileMIME = "i-world/i-vrml"
			Case ".ivy"
				strFileMIME = "application/x-livescreen"
			Case ".jam"
				strFileMIME = "audio/x-jam"
			Case ".jav"
				strFileMIME = "text/plain"
		'	Case ".jav"
		'		strFileMIME = "text/x-java-source"
			Case ".java"
				strFileMIME = "text/plain"
		'	Case ".java"
		'		strFileMIME = "text/x-java-source"
			Case ".jcm"
				strFileMIME = "application/x-java-commerce"
			Case ".jfif"
				strFileMIME = "image/jpeg"
		'	Case ".jfif"
		'		strFileMIME = "image/pjpeg"
			Case ".jfif-tbnl"
				strFileMIME = "image/jpeg"
			Case ".jpe"
				strFileMIME = "image/jpeg"
			Case ".jpe"
				strFileMIME = "image/pjpeg"
			Case ".jpeg"
				strFileMIME = "image/jpeg"
		'	Case ".jpeg"
		'		strFileMIME = "image/pjpeg"
			Case ".jpg"
				strFileMIME = "image/jpeg"
		'	Case ".jpg"
		'		strFileMIME = "image/pjpeg"
			Case ".jps"
				strFileMIME = "image/x-jps"
			Case ".js"
				strFileMIME = "application/x-javascript"
			Case ".jut"
				strFileMIME = "image/jutvision"
			Case ".kar"
				strFileMIME = "audio/midi"
			Case ".kar"
				strFileMIME = "music/x-karaoke"
		'	Case ".ksh"
		'		strFileMIME = "application/x-ksh"
			Case ".ksh"
				strFileMIME = "text/x-script.ksh"
			Case ".la"
				strFileMIME = "audio/nspaudio"
			Case ".la"
				strFileMIME = "audio/x-nspaudio"
			Case ".lam"
				strFileMIME = "audio/x-liveaudio"
			Case ".latex"
				strFileMIME = "application/x-latex"
			Case ".lha"
				strFileMIME = "application/lha"
		'	Case ".lha"
		'		strFileMIME = "application/octet-stream"
		'	Case ".lha"
		'		strFileMIME = "application/x-lha"
			Case ".lhx"
				strFileMIME = "application/octet-stream"
			Case ".list"
				strFileMIME = "text/plain"
			Case ".lma"
				strFileMIME = "audio/nspaudio"
		'	Case ".lma"
		'		strFileMIME = "audio/x-nspaudio"
			Case ".log"
				strFileMIME = "text/plain"
		'	Case ".lsp"
		'		strFileMIME = "application/x-lisp"
			Case ".lsp"
				strFileMIME = "text/x-script.lisp"
			Case ".lst"
				strFileMIME = "text/plain"
			Case ".lsx"
				strFileMIME = "text/x-la-asf"
			Case ".ltx"
				strFileMIME = "application/x-latex"
		'	Case ".lzh"
		'		strFileMIME = "application/octet-stream"
			Case ".lzh"
				strFileMIME = "application/x-lzh"
			Case ".lzx"
				strFileMIME = "application/lzx"
		'	Case ".lzx"
		'		strFileMIME = "application/octet-stream"
		'	Case ".lzx"
		'		strFileMIME = "application/x-lzx"
			Case ".m"
				strFileMIME = "text/plain"
		'	Case ".m"
		'		strFileMIME = "text/x-m"
			Case ".m1v"
				strFileMIME = "video/mpeg"
			Case ".m2a"
				strFileMIME = "audio/mpeg"
			Case ".m2v"
				strFileMIME = "video/mpeg"
			Case ".m3u"
				strFileMIME = "audio/x-mpequrl"
			Case ".man"
				strFileMIME = "application/x-troff-man"
			Case ".map"
				strFileMIME = "application/x-navimap"
			Case ".mar"
				strFileMIME = "text/plain"
			Case ".mbd"
				strFileMIME = "application/mbedlet"
			Case ".mc$"
				strFileMIME = "application/x-magic-cap-package-1.0"
			Case ".mcd"
				strFileMIME = "application/mcad"
		'	Case ".mcd"
		'		strFileMIME = "application/x-mathcad"
		'	Case ".mcf"
		'		strFileMIME = "image/vasa"
			Case ".mcf"
				strFileMIME = "text/mcf"
			Case ".mcp"
				strFileMIME = "application/netmc"
			Case ".me"
				strFileMIME = "application/x-troff-me"
			Case ".mht"
				strFileMIME = "message/rfc822"
			Case ".mhtml"
				strFileMIME = "message/rfc822"
		'	Case ".mid"
		'		strFileMIME = "application/x-midi"
			Case ".mid"
				strFileMIME = "audio/midi"
		'	Case ".mid"
		'		strFileMIME = "audio/x-mid"
		'	Case ".mid"
		'		strFileMIME = "audio/x-midi"
		'	Case ".mid"
		'		strFileMIME = "music/crescendo"
		'	Case ".mid"
		'		strFileMIME = "x-music/x-midi"
		'	Case ".midi"
		'		strFileMIME = "application/x-midi"
			Case ".midi"
				strFileMIME = "audio/midi"
		'	Case ".midi"
		'		strFileMIME = "audio/x-mid"
		'	Case ".midi"
		'		strFileMIME = "audio/x-midi"
		'	Case ".midi"
		'		strFileMIME = "music/crescendo"
		'	Case ".midi"
		'		strFileMIME = "x-music/x-midi"
		'	Case ".mif"
		'		strFileMIME = "application/x-frame"
			Case ".mif"
				strFileMIME = "application/x-mif"
			Case ".mime"
				strFileMIME = "message/rfc822"
		'	Case ".mime"
		'		strFileMIME = "www/mime"
			Case ".mjf"
				strFileMIME = "audio/x-vnd.AudioExplosion.MjuiceMediaFile"
			Case ".mjpg"
				strFileMIME = "video/x-motion-jpeg"
			Case ".mm"
				strFileMIME = "application/base64"
		'	Case ".mm"
		'		strFileMIME = "application/x-meme"
			Case ".mme"
				strFileMIME = "application/base64"
			Case ".mod"
				strFileMIME = "audio/mod"
		'	Case ".mod"
		'		strFileMIME = "audio/x-mod"
			Case ".moov"
				strFileMIME = "video/quicktime"
			Case ".mov"
				strFileMIME = "video/quicktime"
			Case ".movie"
				strFileMIME = "video/x-sgi-movie"
			Case ".mp2"
				strFileMIME = "audio/mpeg"
		'	Case ".mp2"
		'		strFileMIME = "audio/x-mpeg"
		'	Case ".mp2"
		'		strFileMIME = "video/mpeg"
		'	Case ".mp2"
		'		strFileMIME = "video/x-mpeg"
		'	Case ".mp2"
		''		strFileMIME = "video/x-mpeq2a"
		'	Case ".mp3"
		'		strFileMIME = "audio/mpeg3"
		'	Case ".mp3"
		'		strFileMIME = "audio/x-mpeg-3"
			Case ".mp3"
				strFileMIME = "video/mpeg"
		'	Case ".mp3"
		'		strFileMIME = "video/x-mpeg"
			Case ".mpa"
				strFileMIME = "audio/mpeg"
			Case ".mpa"
				strFileMIME = "video/mpeg"
			Case ".mpc"
				strFileMIME = "application/x-project"
			Case ".mpe"
				strFileMIME = "video/mpeg"
			Case ".mpeg"
				strFileMIME = "video/mpeg"
			Case ".mpg"
				strFileMIME = "audio/mpeg"
		'	Case ".mpg"
		'		strFileMIME = "video/mpeg"
			Case ".mpga"
				strFileMIME = "audio/mpeg"
			Case ".mpp"
				strFileMIME = "application/vnd.ms-project"
			Case ".mpt"
				strFileMIME = "application/x-project"
			Case ".mpv"
				strFileMIME = "application/x-project"
			Case ".mpx"
				strFileMIME = "application/x-project"
			Case ".mrc"
				strFileMIME = "application/marc"
			Case ".ms"
				strFileMIME = "application/x-troff-ms"
			Case ".mv"
				strFileMIME = "video/x-sgi-movie"
			Case ".my"
				strFileMIME = "audio/make"
			Case ".mzz"
				strFileMIME = "application/x-vnd.AudioExplosion.mzz"
			Case ".nap"
				strFileMIME = "image/naplps"
			Case ".naplps"
				strFileMIME = "image/naplps"
			Case ".nc"
				strFileMIME = "application/x-netcdf"
			Case ".ncm"
				strFileMIME = "application/vnd.nokia.configuration-message"
			Case ".nif"
				strFileMIME = "image/x-niff"
			Case ".niff"
				strFileMIME = "image/x-niff"
			Case ".nix"
				strFileMIME = "application/x-mix-transfer"
			Case ".nsc"
				strFileMIME = "application/x-conference"
			Case ".nvd"
				strFileMIME = "application/x-navidoc"
			Case ".o"
				strFileMIME = "application/octet-stream"
			Case ".oda"
				strFileMIME = "application/oda"
			Case ".omc"
				strFileMIME = "application/x-omc"
			Case ".omcd"
				strFileMIME = "application/x-omcdatamaker"
			Case ".omcr"
				strFileMIME = "application/x-omcregerator"
			Case ".p"
				strFileMIME = "text/x-pascal"
			Case ".p10"
				strFileMIME = "application/pkcs10"
			Case ".p10"
				strFileMIME = "application/x-pkcs10"
			Case ".p12"
				strFileMIME = "application/pkcs-12"
			Case ".p12"
				strFileMIME = "application/x-pkcs12"
			Case ".p7a"
				strFileMIME = "application/x-pkcs7-signature"
			Case ".p7c"
				strFileMIME = "application/pkcs7-mime"
			Case ".p7c"
				strFileMIME = "application/x-pkcs7-mime"
			Case ".p7m"
				strFileMIME = "application/pkcs7-mime"
			Case ".p7m"
				strFileMIME = "application/x-pkcs7-mime"
			Case ".p7r"
				strFileMIME = "application/x-pkcs7-certreqresp"
			Case ".p7s"
				strFileMIME = "application/pkcs7-signature"
			Case ".part"
				strFileMIME = "application/pro_eng"
			Case ".pas"
				strFileMIME = "text/pascal"
			Case ".pbm"
				strFileMIME = "image/x-portable-bitmap"
			Case ".pcl"
				strFileMIME = "application/vnd.hp-PCL"
			Case ".pcl"
				strFileMIME = "application/x-pcl"
			Case ".pct"
				strFileMIME = "image/x-pict"
			Case ".pcx"
				strFileMIME = "image/x-pcx"
			Case ".pdb"
				strFileMIME = "chemical/x-pdb"
			Case ".pdf"
				strFileMIME = "application/pdf"
				strIconName_Small			= "icon_aacrobat_small.gif"
				strIconName_Small_Published = "icon_aacrobat_small_on.gif"
				strIconName_Large			= "icon_aacrobat_small.gif"
				strIconName_Large_Published = "icon_aacrobat_small_on.gif"
			Case ".pfunk"
				strFileMIME = "audio/make"
		'	Case ".pfunk"
		'		strFileMIME = "audio/make.my.funk"
			Case ".pgm"
				strFileMIME = "image/x-portable-graymap"
			Case ".pgm"
				strFileMIME = "image/x-portable-greymap"
			Case ".pic"
				strFileMIME = "image/pict"
			Case ".pict"
				strFileMIME = "image/pict"
			Case ".pkg"
				strFileMIME = "application/x-newton-compatible-pkg"
			Case ".pko"
				strFileMIME = "application/vnd.ms-pki.pko"
		'	Case ".pl"
		'		strFileMIME = "text/plain"
			Case ".pl"
				strFileMIME = "text/x-script.perl"
			Case ".plx"
				strFileMIME = "application/x-PiXCLscript"
			Case ".pm"
				strFileMIME = "image/x-xpixmap"
			Case ".pm"
				strFileMIME = "text/x-script.perl-module"
			Case ".pm4"
				strFileMIME = "application/x-pagemaker"
			Case ".pm5"
				strFileMIME = "application/x-pagemaker"
			Case ".png"
				strFileMIME = "image/png"
			Case ".pnm"
				strFileMIME = "application/x-portable-anymap"
			Case ".pnm"
				strFileMIME = "image/x-portable-anymap"
			Case ".pot"
				strFileMIME = "application/mspowerpoint"
				strIconName_Small			= "icon_mspowerpoint_small.gif"
				strIconName_Small_Published = "icon_mspowerpoint_small_on.gif"
				strIconName_Large			= "icon_mspowerpoint_small.gif"
				strIconName_Large_Published = "icon_mspowerpoint_small_on.gif"
			Case ".pot"
				strFileMIME = "application/vnd.ms-powerpoint"
				strIconName_Small			= "icon_mspowerpoint_small.gif"
				strIconName_Small_Published = "icon_mspowerpoint_small_on.gif"
				strIconName_Large			= "icon_mspowerpoint_small.gif"
				strIconName_Large_Published = "icon_mspowerpoint_small_on.gif"
			Case ".pov"
				strFileMIME = "model/x-pov"
			Case ".ppa"
				strFileMIME = "application/vnd.ms-powerpoint"
				strIconName_Small			= "icon_mspowerpoint_small.gif"
				strIconName_Small_Published = "icon_mspowerpoint_small_on.gif"
				strIconName_Large			= "icon_mspowerpoint_small.gif"
				strIconName_Large_Published = "icon_mspowerpoint_small_on.gif"
			Case ".ppm"
				strFileMIME = "image/x-portable-pixmap"
		'	Case ".pps"
		'		strFileMIME = "application/mspowerpoint"
			Case ".pps"
				strFileMIME = "application/vnd.ms-powerpoint"
				strIconName_Small			= "icon_mspowerpoint_small.gif"
				strIconName_Small_Published = "icon_mspowerpoint_small_on.gif"
				strIconName_Large			= "icon_mspowerpoint_small.gif"
				strIconName_Large_Published = "icon_mspowerpoint_small_on.gif"
		'	Case ".ppt"
		'		strFileMIME = "application/mspowerpoint"
		'	Case ".ppt"
		'		strFileMIME = "application/powerpoint"
			Case ".ppt"
				strFileMIME = "application/vnd.ms-powerpoint"
				strIconName_Small			= "icon_mspowerpoint_small.gif"
				strIconName_Small_Published = "icon_mspowerpoint_small_on.gif"
				strIconName_Large			= "icon_mspowerpoint_small.gif"
				strIconName_Large_Published = "icon_mspowerpoint_small_on.gif"
		'	Case ".ppt"
		'		strFileMIME = "application/x-mspowerpoint"
			Case ".ppz"
				strFileMIME = "application/mspowerpoint"
				strIconName_Small			= "icon_mspowerpoint_small.gif"
				strIconName_Small_Published = "icon_mspowerpoint_small_on.gif"
				strIconName_Large			= "icon_mspowerpoint_small.gif"
				strIconName_Large_Published = "icon_mspowerpoint_small_on.gif"
			Case ".pre"
				strFileMIME = "application/x-freelance"
			Case ".prt"
				strFileMIME = "application/pro_eng"
			Case ".ps"
				strFileMIME = "application/postscript"
				strIconName_Small			= "icon_aacrobat_small.gif"
				strIconName_Small_Published = "icon_aacrobat_small_on.gif"
				strIconName_Large			= "icon_aacrobat_small.gif"
				strIconName_Large_Published = "icon_aacrobat_small_on.gif"
			Case ".psd"
				strFileMIME = "application/octet-stream"
				strIconName_Small			= "icon_aphotoshop_small.gif"
				strIconName_Small_Published = "icon_aphotoshop_small_on.gif"
				strIconName_Large			= "icon_aphotoshop_small.gif"
				strIconName_Large_Published = "icon_aphotoshop_small_on.gif"
			Case ".pub"
				strFileMIME = "application/mspublisher"
				strIconName_Small			= "icon_mspublisher_small.gif"
				strIconName_Small_Published = "icon_mspublisher_small_on.gif"
				strIconName_Large			= "icon_mspublisher_small.gif"
				strIconName_Large_Published = "icon_mspublisher_small_on.gif"
			Case ".pvu"
				strFileMIME = "paleovu/x-pv"
			Case ".pwz"
				strFileMIME = "application/vnd.ms-powerpoint"
				strIconName_Small			= "icon_mspowerpoint_small.gif"
				strIconName_Small_Published = "icon_mspowerpoint_small_on.gif"
				strIconName_Large			= "icon_mspowerpoint_small.gif"
				strIconName_Large_Published = "icon_mspowerpoint_small_on.gif"
			Case ".py"
				strFileMIME = "text/x-script.phyton"
			Case ".pyc"
				strFileMIME = "applicaiton/x-bytecode.python"
			Case ".qcp"
				strFileMIME = "audio/vnd.qcelp"
			Case ".qd3"
				strFileMIME = "x-world/x-3dmf"
			Case ".qd3d"
				strFileMIME = "x-world/x-3dmf"
			Case ".qif"
				strFileMIME = "image/x-quicktime"
			Case ".qt"
				strFileMIME = "video/quicktime"
			Case ".qtc"
				strFileMIME = "video/x-qtc"
			Case ".qti"
				strFileMIME = "image/x-quicktime"
			Case ".qtif"
				strFileMIME = "image/x-quicktime"
		'	Case ".ra"
		'		strFileMIME = "audio/x-pn-realaudio"
		'	Case ".ra"
		'		strFileMIME = "audio/x-pn-realaudio-plugin"
			Case ".ra"
				strFileMIME = "audio/x-realaudio"
			Case ".ram"
				strFileMIME = "audio/x-pn-realaudio"
		'	Case ".ras"
		'		strFileMIME = "application/x-cmu-raster"
		'	Case ".ras"
		'		strFileMIME = "image/cmu-raster"
			Case ".ras"
				strFileMIME = "image/x-cmu-raster"
			Case ".rast"
				strFileMIME = "image/cmu-raster"
			Case ".rexx"
				strFileMIME = "text/x-script.rexx"
			Case ".rf"
				strFileMIME = "image/vnd.rn-realflash"
			Case ".rgb"
				strFileMIME = "image/x-rgb"
			Case ".rm"
				strFileMIME = "application/vnd.rn-realmedia"
		'	Case ".rm"
		'		strFileMIME = "audio/x-pn-realaudio"
			Case ".rmi"
				strFileMIME = "audio/mid"
			Case ".rmm"
				strFileMIME = "audio/x-pn-realaudio"
			Case ".rmp"
				strFileMIME = "audio/x-pn-realaudio"
			Case ".rmp"
				strFileMIME = "audio/x-pn-realaudio-plugin"
			Case ".rng"
				strFileMIME = "application/ringing-tones"
			Case ".rng"
				strFileMIME = "application/vnd.nokia.ringing-tone"
			Case ".rnx"
				strFileMIME = "application/vnd.rn-realplayer"
			Case ".roff"
				strFileMIME = "application/x-troff"
			Case ".rp"
				strFileMIME = "image/vnd.rn-realpix"
			Case ".rpm"
				strFileMIME = "audio/x-pn-realaudio-plugin"
			Case ".rt"
				strFileMIME = "text/richtext"
		'	Case ".rt"
		'		strFileMIME = "text/vnd.rn-realtext"
		'	Case ".rtf"
		'		strFileMIME = "application/rtf"
		'	Case ".rtf"
		'		strFileMIME = "application/x-rtf"
		'	Case ".rtf"
				strFileMIME = "text/richtext"
		'	Case ".rtx"
		'		strFileMIME = "application/rtf"
			Case ".rtx"
				strFileMIME = "text/richtext"
			Case ".rv"
				strFileMIME = "video/vnd.rn-realvideo"
			Case ".s"
				strFileMIME = "text/x-asm"
			Case ".s3m"
				strFileMIME = "audio/s3m"
			Case ".saveme"
				strFileMIME = "application/octet-stream"
			Case ".sbk"
				strFileMIME = "application/x-tbook"
			Case ".scm"
				strFileMIME = "application/x-lotusscreencam"
		'	Case ".scm"
		'		strFileMIME = "text/x-script.guile"
		'	Case ".scm"
		'		strFileMIME = "text/x-script.scheme"
		'	Case ".scm"
		'		strFileMIME = "video/x-scm"
			Case ".sdml"
				strFileMIME = "text/plain"
			Case ".sdp"
				strFileMIME = "application/sdp"
		'	Case ".sdp"
		'		strFileMIME = "application/x-sdp"
			Case ".sdr"
				strFileMIME = "application/sounder"
			Case ".sea"
				strFileMIME = "application/sea"
		'	Case ".sea"
		'		strFileMIME = "application/x-sea"
			Case ".set"
				strFileMIME = "application/set"
			Case ".sgm"
				strFileMIME = "text/sgml"
		'	Case ".sgm"
		'		strFileMIME = "text/x-sgml"
			Case ".sgml"
				strFileMIME = "text/sgml"
		'	Case ".sgml"
		'		strFileMIME = "text/x-sgml"
		'	Case ".sh"
		'		strFileMIME = "application/x-bsh"
		'	Case ".sh"
		'		strFileMIME = "application/x-sh"
		''	Case ".sh"
		'		strFileMIME = "application/x-shar"
			Case ".sh"
				strFileMIME = "text/x-script.sh"
		'	Case ".shar"
		'		strFileMIME = "application/x-bsh"
			Case ".shar"
				strFileMIME = "application/x-shar"
			Case ".shtml"
				strFileMIME = "text/html"
		'	Case ".shtml"
		'		strFileMIME = "text/x-server-parsed-html"
			Case ".sid"
				strFileMIME = "audio/x-psid"
		'	Case ".sit"
		'		strFileMIME = "application/x-sit"
			Case ".sit"
				strFileMIME = "application/x-stuffit"
			Case ".skd"
				strFileMIME = "application/x-koan"
			Case ".skm"
				strFileMIME = "application/x-koan"
			Case ".skp"
				strFileMIME = "application/x-koan"
			Case ".skt"
				strFileMIME = "application/x-koan"
			Case ".sl"
				strFileMIME = "application/x-seelogo"
			Case ".smi"
				strFileMIME = "application/smil"
			Case ".smil"
				strFileMIME = "application/smil"
			Case ".snd"
				strFileMIME = "audio/basic"
		'	Case ".snd"
		'		strFileMIME = "audio/x-adpcm"
			Case ".sol"
				strFileMIME = "application/solids"
		'	Case ".spc"
		'		strFileMIME = "application/x-pkcs7-certificates"
			Case ".spc"
				strFileMIME = "text/x-speech"
			Case ".spl"
				strFileMIME = "application/futuresplash"
			Case ".spr"
				strFileMIME = "application/x-sprite"
			Case ".sprite"
				strFileMIME = "application/x-sprite"
			Case ".src"
				strFileMIME = "application/x-wais-source"
			Case ".ssi"
				strFileMIME = "text/x-server-parsed-html"
			Case ".ssm"
				strFileMIME = "application/streamingmedia"
			Case ".sst"
				strFileMIME = "application/vnd.ms-pki.certstore"
			Case ".step"
				strFileMIME = "application/step"
		'	Case ".stl"
		'		strFileMIME = "application/sla"
			Case ".stl"
				strFileMIME = "application/vnd.ms-pki.stl"
		'	Case ".stl"
		'		strFileMIME = "application/x-navistyle"
			Case ".stp"
				strFileMIME = "application/step"
			Case ".sv4cpio"
				strFileMIME = "application/x-sv4cpio"
			Case ".sv4crc"
				strFileMIME = "application/x-sv4crc"
			Case ".svf"
				strFileMIME = "image/vnd.dwg"
		'	Case ".svf"
		'		strFileMIME = "image/x-dwg"
		'	Case ".svr"
		'		strFileMIME = "application/x-world"
			Case ".svr"
				strFileMIME = "x-world/x-svr"
			Case ".swf"
				strFileMIME = "application/x-shockwave-flash"
				strIconName_Small			= "icon_flash_small.gif"
				strIconName_Small_Published = "icon_flash_small_on.gif"
				strIconName_Large			= "icon_flash_small.gif"
				strIconName_Large_Published = "icon_flash_small_on.gif"
			Case ".t"
				strFileMIME = "application/x-troff"
			Case ".talk"
				strFileMIME = "text/x-speech"
			Case ".tar"
				strFileMIME = "application/x-tar"
			Case ".tbk"
				strFileMIME = "application/toolbook"
		'	Case ".tbk"
		'		strFileMIME = "application/x-tbook"
		'	Case ".tcl"
		'		strFileMIME = "application/x-tcl"
			Case ".tcl"
				strFileMIME = "text/x-script.tcl"
			Case ".tcsh"
				strFileMIME = "text/x-script.tcsh"
			Case ".tex"
				strFileMIME = "application/x-tex"
			Case ".texi"
				strFileMIME = "application/x-texinfo"
			Case ".texinfo"
				strFileMIME = "application/x-texinfo"
		'	Case ".text"
		'		strFileMIME = "application/plain"
			Case ".text"
				strFileMIME = "text/plain"
		'	Case ".tgz"
		'		strFileMIME = "application/gnutar"
			Case ".tgz"
				strFileMIME = "application/x-compressed"
			Case ".tif"
				strFileMIME = "image/tiff"
		'	Case ".tif"
		'		strFileMIME = "image/x-tiff"
			Case ".tiff"
				strFileMIME = "image/tiff"
		'	Case ".tiff"
		'		strFileMIME = "image/x-tiff"
			Case ".tr"
				strFileMIME = "application/x-troff"
			Case ".tsi"
				strFileMIME = "audio/tsp-audio"
		'	Case ".tsp"
		'		strFileMIME = "application/dsptype"
			Case ".tsp"
				strFileMIME = "audio/tsplayer"
			Case ".tsv"
				strFileMIME = "text/tab-separated-values"
			Case ".turbot"
				strFileMIME = "image/florian"
			Case ".txt"
				strFileMIME = "text/plain"
			Case ".uil"
				strFileMIME = "text/x-uil"
			Case ".uni"
				strFileMIME = "text/uri-list"
			Case ".unis"
				strFileMIME = "text/uri-list"
			Case ".unv"
				strFileMIME = "application/i-deas"
			Case ".uri"
				strFileMIME = "text/uri-list"
			Case ".uris"
				strFileMIME = "text/uri-list"
			Case ".ustar"
				strFileMIME = "application/x-ustar"
		'	Case ".ustar"
		'		strFileMIME = "multipart/x-ustar"
			Case ".uu"
				strFileMIME = "application/octet-stream"
			Case ".uu"
				strFileMIME = "text/x-uuencode"
			Case ".uue"
				strFileMIME = "text/x-uuencode"
			Case ".vcd"
				strFileMIME = "application/x-cdlink"
			Case ".vcs"
				strFileMIME = "text/x-vCalendar"
			Case ".vda"
				strFileMIME = "application/vda"
			Case ".vdo"
				strFileMIME = "video/vdo"
			Case ".vew"
				strFileMIME = "application/groupwise"
			Case ".viv"
				strFileMIME = "video/vivo"
			Case ".viv"
				strFileMIME = "video/vnd.vivo"
			Case ".vivo"
				strFileMIME = "video/vivo"
		'	Case ".vivo"
		'		strFileMIME = "video/vnd.vivo"
			Case ".vmd"
				strFileMIME = "application/vocaltec-media-desc"
			Case ".vmf"
				strFileMIME = "application/vocaltec-media-file"
			Case ".voc"
				strFileMIME = "audio/voc"
		'	Case ".voc"
		'		strFileMIME = "audio/x-voc"
			Case ".vos"
				strFileMIME = "video/vosaic"
			Case ".vox"
				strFileMIME = "audio/voxware"
			Case ".vqe"
				strFileMIME = "audio/x-twinvq-plugin"
			Case ".vqf"
				strFileMIME = "audio/x-twinvq"
			Case ".vql"
				strFileMIME = "audio/x-twinvq-plugin"
			Case ".vrml"
				strFileMIME = "application/x-vrml"
		'	Case ".vrml"
		'		strFileMIME = "model/vrml"
		'	Case ".vrml"
		'		strFileMIME = "x-world/x-vrml"
			Case ".vrt"
				strFileMIME = "x-world/x-vrt"
			Case ".vsd"
				strFileMIME = "application/x-visio"
				strIconName_Small			= "icon_msvisio_small.gif"
				strIconName_Small_Published = "icon_msvisio_small_on.gif"
				strIconName_Large			= "icon_msvisio_small.gif"
				strIconName_Large_Published = "icon_msvisio_small_on.gif"
			Case ".vst"
				strFileMIME = "application/x-visio"
				strIconName_Small			= "icon_msvisio_small.gif"
				strIconName_Small_Published = "icon_msvisio_small_on.gif"
				strIconName_Large			= "icon_msvisio_small.gif"
				strIconName_Large_Published = "icon_msvisio_small_on.gif"
			Case ".vsw"
				strFileMIME = "application/x-visio"
				strIconName_Small			= "icon_msvisio_small.gif"
				strIconName_Small_Published = "icon_msvisio_small_on.gif"
				strIconName_Large			= "icon_msvisio_small.gif"
				strIconName_Large_Published = "icon_msvisio_small_on.gif"
			Case ".w60"
				strFileMIME = "application/wordperfect6.0"
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			Case ".w61"
				strFileMIME = "application/wordperfect6.1"
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			Case ".w6w"
				strFileMIME = "application/msword"
				strIconName_Small			= "icon_msword_small.gif"
				strIconName_Small_Published = "icon_msword_small_on.gif"
				strIconName_Large			= "icon_msword_small.gif"
				strIconName_Large_Published = "icon_msword_small_on.gif"
			Case ".wav"
				strFileMIME = "audio/wav"
		'	Case ".wav"
		'		strFileMIME = "audio/x-wav"
			Case ".wb1"
				strFileMIME = "application/x-qpro"
			Case ".wbmp"
				strFileMIME = "image/vnd.wap.wbmp"
			Case ".web"
				strFileMIME = "application/vnd.xara"
			Case ".wiz"
				strFileMIME = "application/msword"
				strIconName_Small			= "icon_msword_small.gif"
				strIconName_Small_Published = "icon_msword_small_on.gif"
				strIconName_Large			= "icon_msword_small.gif"
				strIconName_Large_Published = "icon_msword_small_on.gif"
			Case ".wk1"
				strFileMIME = "application/x-123"
			Case ".wmf"
				strFileMIME = "windows/metafile"
				strIconName_Small			= "icon_windowsmedia_small.gif"
				strIconName_Small_Published = "icon_windowsmedia_small_on.gif"
				strIconName_Large			= "icon_windowsmedia_small.gif"
				strIconName_Large_Published = "icon_windowsmedia_small_on.gif"
			Case ".wml"
				strFileMIME = "text/vnd.wap.wml"
			Case ".wmlc"
				strFileMIME = "application/vnd.wap.wmlc"
			Case ".wmls"
				strFileMIME = "text/vnd.wap.wmlscript"
			Case ".wmlsc"
				strFileMIME = "application/vnd.wap.wmlscriptc"
			Case ".word"
				strFileMIME = "application/msword"
				strIconName_Small			= "icon_msword_small.gif"
				strIconName_Small_Published = "icon_msword_small_on.gif"
				strIconName_Large			= "icon_msword_small.gif"
				strIconName_Large_Published = "icon_msword_small_on.gif"
			Case ".wp"
				strFileMIME = "application/wordperfect"
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			Case ".wp5"
				strFileMIME = "application/wordperfect"
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			Case ".wp5"
				strFileMIME = "application/wordperfect6.0"
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			Case ".wp6"
				strFileMIME = "application/wordperfect"
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			Case ".wpd"
				strFileMIME = "application/wordperfect"
		'	Case ".wpd"
		'		strFileMIME = "application/x-wpwin"
			Case ".wq1"
				strFileMIME = "application/x-lotus"
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			Case ".wri"
				strFileMIME = "application/mswrite"
				strIconName_Small			= "icon_msword_small.gif"
				strIconName_Small_Published = "icon_msword_small_on.gif"
				strIconName_Large			= "icon_msword_small.gif"
				strIconName_Large_Published = "icon_msword_small_on.gif"
		'	Case ".wri"
		'		strFileMIME = "application/x-wri"
		'	Case ".wrl"
		'		strFileMIME = "application/x-world"
			Case ".wrl"
				strFileMIME = "model/vrml"
		'	Case ".wrl"
		'		strFileMIME = "x-world/x-vrml"
			Case ".wrz"
				strFileMIME = "model/vrml"
		'	Case ".wrz"
		'		strFileMIME = "x-world/x-vrml"
			Case ".wsc"
				strFileMIME = "text/scriplet"
			Case ".wsrc"
				strFileMIME = "application/x-wais-source"
			Case ".wtk"
				strFileMIME = "application/x-wintalk"
			Case ".xbm"
				strFileMIME = "image/x-xbitmap"
		'	Case ".xbm"
		'		strFileMIME = "image/x-xbm"
		'	Case ".xbm"
		'		strFileMIME = "image/xbm"
			Case ".xdr"
				strFileMIME = "video/x-amt-demorun"
			Case ".xgz"
				strFileMIME = "xgl/drawing"
			Case ".xif"
				strFileMIME = "image/vnd.xiff"
			Case ".xl"
				strFileMIME = "application/excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xla"
		'		strFileMIME = "application/excel"
			Case ".xla"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xla"
		'		strFileMIME = "application/x-excel"
		'	Case ".xla"
		'		strFileMIME = "application/x-msexcel"
		'	Case ".xlb"
		'		strFileMIME = "application/excel"
			Case ".xlb"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xlb"
		'		strFileMIME = "application/x-excel"
		'	Case ".xlc"
		'		strFileMIME = "application/excel"
			Case ".xlc"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xlc"
		'		strFileMIME = "application/x-excel"
			Case ".xld"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xld"
		'		strFileMIME = "application/excel"
		'	Case ".xld"
		'		strFileMIME = "application/x-excel"
		'	Case ".xlk"
		'		strFileMIME = "application/excel"
			Case ".xlk"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xll"
		'		strFileMIME = "application/excel"
			Case ".xll"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xll"
		'		strFileMIME = "application/x-excel"
		'	Case ".xlm"
		'		strFileMIME = "application/excel"
			Case ".xlm"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xlm"
		'		strFileMIME = "application/x-excel"
		'	Case ".xls"
		'		strFileMIME = "application/excel"
			Case ".xls"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xls"
		'		strFileMIME = "application/x-excel"
		'	Case ".xls"
		'		strFileMIME = "application/x-msexcel"
		'	Case ".xlt"
		'		strFileMIME = "application/excel"
			Case ".xlt"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xlv"
		'		strFileMIME = "application/excel"
			Case ".xlv"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xlw"
		'		strFileMIME = "application/excel"
			Case ".xlw"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
		'	Case ".xlw"
		'		strFileMIME = "application/x-excel"
			Case ".xlw"
				strFileMIME = "application/vnd.ms-excel"
				strIconName_Small			= "icon_msexcel_small.gif"
				strIconName_Small_Published = "icon_msexcel_small_on.gif"
				strIconName_Large			= "icon_msexcel_small.gif"
				strIconName_Large_Published = "icon_msexcel_small_on.gif"
			Case ".xm"
				strFileMIME = "audio/xm"
		'	Case ".xml"
		'		strFileMIME = "application/xml"
			Case ".xml"
				strFileMIME = "text/xml"
			Case ".xmz"
				strFileMIME = "xgl/movie"
			Case ".xpix"
				strFileMIME = "application/x-vnd.ls-xpix"
		'	Case ".xpm"
		'		strFileMIME = "image/x-xpixmap"
			Case ".xpm"
				strFileMIME = "image/xpm"
			Case ".x-png"
				strFileMIME = "image/png"
			Case ".xsr"
				strFileMIME = "video/x-amt-showrun"
			Case ".xwd"
				strFileMIME = "image/x-xwd"
		'	Case ".xwd"
		'		strFileMIME = "image/x-xwindowdump"
			Case ".xyz"
				strFileMIME = "chemical/x-pdb"
		'	Case ".z"
		'		strFileMIME = "application/x-compress"
			Case ".z"
				strFileMIME = "application/x-compressed"
			Case ".zip"
				strFileMIME = "application/x-compressed"
				strIconName_Small			= "icon_winzip_small.gif"
				strIconName_Small_Published = "icon_winzip_small_on.gif"
				strIconName_Large			= "icon_winzip_small.gif"
				strIconName_Large_Published = "icon_winzip_small_on.gif"
		'	Case ".zip"
		'		strFileMIME = "application/x-zip-compressed"
		'	Case ".zip"
		'		strFileMIME = "application/zip"
		'	Case ".zip"
		'		strFileMIME = "multipart/x-zip"
			Case ".zoo"
				strFileMIME = "application/octet-stream"
			Case ".zsh"
				strFileMIME = "text/x-script.zsh"
		End Select
	end if

	if strFileMIME <> "" then
		'Set all that slipped through the app-specific settings above
		if strIconName_Small = "" or strIconName_Small_Published = "" then
			if Instr(strFileMIME, "audio/") > 0 then
				strIconName_Small			= "icon_gensound_small.gif"
				strIconName_Small_Published = "icon_gensound_small_on.gif"					
			elseif Instr(strFileMIME, "video/") > 0 then
				strIconName_Small			= "icon_genvideo_small.gif"
				strIconName_Small_Published = "icon_genvideo_small_on.gif"					
			elseif Instr(strFileMIME, "image/") > 0 then
				strIconName_Small			= "icon_genimage_small.gif"
				strIconName_Small_Published = "icon_genimage_small_on.gif"
			elseif Instr(strFileMIME, "text/") > 0 then
				strIconName_Small			= "icon_gentext_small.gif"
				strIconName_Small_Published = "icon_gentext_small_on.gif"
			elseif Instr(strFileMIME, "compress/") > 0 then
				strIconName_Small			= "icon_winzip_small.gif"
				strIconName_Small_Published = "icon_winzip_small_on.gif"
			else
				strIconName_Small			= "view.gif"
				strIconName_Small_Published = "view.gif"
			end if
		end if
		if strIconName_Large = "" or strIconName_Large_Published = "" then
			if Instr(strFileMIME, "audio/") > 0 then
				strIconName_Large			= "icon_gensound_small.gif"
				strIconName_Large_Published = "icon_gensound_small_on.gif"					
			elseif Instr(strFileMIME, "video/") > 0 then
				strIconName_Large			= "icon_genvideo_small.gif"
				strIconName_Large_Published = "icon_genvideo_small_on.gif"					
			elseif Instr(strFileMIME, "image/") > 0 then
				strIconName_Large			= "icon_genimage_small.gif"
				strIconName_Large_Published = "icon_genimage_small_on.gif"
			elseif Instr(strFileMIME, "text/") > 0 then
				strIconName_Large			= "icon_gentext_small.gif"
				strIconName_Large_Published = "icon_gentext_small_on.gif"
			elseif Instr(strFileMIME, "compress/") > 0 then
				strIconName_Large			= "icon_winzip_small.gif"
				strIconName_Large_Published = "icon_winzip_small_on.gif"
			else
				strIconName_Large			= "view.gif"
				strIconName_Large_Published = "view.gif"
			end if
		end if
	else	'if 1 = 2 then
		'Set all that slipped through the cracks
		strIconName_Small			= "view.gif"
		strIconName_Small_Published = "view.gif"
		strIconName_Large			= "view.gif"
		strIconName_Large_Published = "view.gif"
	end if

	
	if CBool(bitIsPublished) then
		if CBool(bitIconSize) then
			getFileIcon = strIconName_Large_Published
		else
			getFileIcon = strIconName_Small_Published
		end if
	else
		if CBool(bitIconSize) then
			getFileIcon = strIconName_Large
		else
			getFileIcon = strIconName_Small
		end if
	end if
end function

%>