var g_strHeCssWindowText = "black"
var g_strHeCssWindow="window"
var g_strHeCssThreedFace = "#DAEAFD"
var g_strHeCssThreedHighlight = "#FFFFFF"
var g_strHeCssThreedShadow = "#E3E3C9"
var g_strHeCssBtnFaceU = "#DEDBD6"
var g_strHeCssBtnFaceD = "#DEDBEE"
var g_strHeCssBtnFaceO = "#BEBBCE"
var g_strHeCssBtnHighlight = "#08246B"
var g_strHeCssBtnShadow = "#08246B"
var g_strHeCssMenuText = "black"
var g_strHeCssMenuBack = "#FFFBF7"
var g_strHeCssMenuTopLeft = "#636563"
var g_strHeCssMenuBottomRight = "#636563"
var g_strHeCssMenuGrayText = "#848284"
var g_strHeCssMenuSeparatorTop = "#FFFBF7"
var g_strHeCssMenuSeparatorBottom = "#949294"
var g_strHeCssMenuUText = "black"
var g_strHeCssMenuUBack = "#B5BED6"
var g_strHeCssMenuUTopLeft = "#08246B"
var g_strHeCssMenuUBottomRight = "#08246B"
var g_strHeCssMenuBorderWidth = 1
var g_strHeCssEditorBorderColor = "#3B619C"
var g_strHeCssBtnHeight = 22

g_strHeCssToolBarBack="position:relative;left:0px;top:0px;padding:0px;background-image: url("+g_strHtmlEditPath+"htmleditimg/blue-toolbarbg.gif);background-color:#F0F0EA;border-width: 0px;overflow:hidden;text-align:left"
g_strHeCssToolBar="margin-right: 6px"
g_strHeCssBtn="cursor:pointer;margin:1px"
g_strHeCssBtnOver="cursor:pointer;padding:0px;background-image:url("+g_strHtmlEditPath+"htmleditimg/blue-btnbackfocus.gif);border:1px solid #000080"
g_strHeCssBtnDown="cursor:pointer;padding:0px;background-image:url("+g_strHtmlEditPath+"htmleditimg/blue-btnbackdown.gif);border:1px solid #000080"
g_strHeCssBtnDownOver="cursor:pointer;padding:0px;background-image:url("+g_strHtmlEditPath+"htmleditimg/blue-btnbackfocus.gif);border:1px solid #000080"
g_strHeCssBtnDisabledIE="cursor:pointer;padding:0px;border:solid;border-width:1px;background-color:"+g_strHeCssThreedFace+";Border-Top-Color:"+g_strHeCssThreedFace + "; Border-Left-Color:" + g_strHeCssThreedFace + "; Border-Bottom-Color:" + g_strHeCssThreedFace + "; Border-Right-Color:" + g_strHeCssThreedFace + "; filter: Chroma(Color=red) Alpha(Opacity=25); backgroundColor: red"
g_strHeCssBtnDisabled="cursor:pointer;padding:0px;border:solid;border-width:1px;background-color:"+g_strHeCssThreedFace+";Border-Top-Color:"+g_strHeCssThreedFace + "; Border-Left-Color:" + g_strHeCssThreedFace + "; Border-Bottom-Color:" + g_strHeCssThreedFace + "; Border-Right-Color:" + g_strHeCssThreedFace + "; visibility: hidden"
g_strHeCssText="cursor:default;font-family:tahoma,sans-serif;font-size:8pt;color:"+g_strHeCssWindowText
g_strHeCssSelect="cursor:default;font-family:tahoma,sans-serif;font-size:8pt;background-color:#FFF4CC;color:black;border:1px solid #4649C4"
g_strHeCssStatusBar="position:relative;left:0px;top:0px;padding:1px;background-color:"+g_strHeCssThreedFace+";border:1px solid " + g_strHeCssThreedShadow + "; border-top-color:" + g_strHeCssThreedHighlight + "; border-left-color:" + g_strHeCssThreedHighlight + ";overflow:hidden;text-align:left"
g_strHeCssStatusBox="cursor:default;font-family:tahoma,sans-serif;color:"+g_strHeCssWindowText+";background-color:"+g_strHeCssThreedFace+";font-size:8pt; border-width:1px; border-style:solid; border-color:" + g_strHeCssThreedShadow + "; border-right-color:" + g_strHeCssThreedHighlight + "; border-bottom-color:"+g_strHeCssThreedHighlight+";text-align:center;padding-left:15px;padding-right:10px"

